### PR TITLE
fix(SDK-imports): Update imports in testing view controllers.

### PR DESCRIPTION
**Pull request by sayaansaha**

### CODE REVIEW

**Review by alexisoyama — APPROVED** [review]

**Comment by Enuviel** [comment]
hm, I do not have any  compile error

**Comment by alexisoyama** [comment]
btw imports changes with having STATIC or not. Check TestApp for reference. We should probably do something identical here.

**Comment by sayaansaha** [comment]
@alexisoyama  I will check out the TestApp as well.

**Comment by sayaansaha** [comment]
@alexisoyama I tested my changes in this PR with Static builds and they build just fine and the app starts up. However I didnt do a whole  QA on it. If you think its still risky I can change it to be more like the old TestApp

```// Follow the instructions in Getting Started to set up the sample project.
#if STATIC
#import "Leanplum.h"
#import "LeanplumUIEditor.h"
#else
#import "Leanplum/Leanplum.h"
#import "LeanplumUIEditor/LeanplumUIEditor.h"
#endif```

**Comment by alexisoyama** [comment]
Make sure you `clean` it before you build/run. Sometimes it doesn't update it properly. 

But after you test it, and it works on both dynamic/static then feel free to merge it.

**Comment by sayaansaha** [comment]
Yeah tested it and it works fine, i'm going to squash and merge

**Pull request merged**
